[package]
name = "wasm-actions-build"
version = "0.1.1"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
yaml-rust = "0.4.5"
syn = { version = "2.0.110", features = ["parsing", "full"] }
serde_json = "1.0.145"
wasm-actions-parse = { path = "../wasm-actions-parse" }

[dev-dependencies]
