[workspace]
resolver = "3"
members = [
    "crates/wasm-actions",
    "crates/wasm-actions-core",
    "crates/wasm-actions-derive",
    "crates/wasm-actions-log",
    "crates/wasm-actions-macro",
    "crates/wasm-actions-prelude"
]
