[package]
name = "wasm-actions"
version = "0.3.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[features]

[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/log",
    "crates/macro",
    "crates/prelude"
]

[dependencies]
wasm-actions-core = { path = "crates/core" }
wasm-actions-log = { path = "crates/log" }
wasm-actions-macro = { path = "crates/macro" }
wasm-actions-prelude = { path = "crates/prelude" }
wasm-bindgen-futures = "0.4.55"
async-once-cell = "0.5.4"
log = "0.4.28"

[dev-dependencies]
trybuild = "1.0.114"
wasm-bindgen-test = "0.3.55"
