[package]
name = "wasm-actions-node-sys"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[features]
default = ["fs"]
fs = []
microtasks = []

[dependencies]
wasm-bindgen = "0.2.106"
js-sys = { version = "0.3.83" }

[dev-dependencies]
