[package]
name = "wasm-actions-futures"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[features]

[dependencies]
js-sys = { version = "0.3.83" }
wasm-actions-node-sys = { path = "../wasm-actions-node-sys", features = ["microtasks"]}
wasm-bindgen = "0.2.106"
wasm-bindgen-futures = { version = "0.4.56", default-features = false }

[dev-dependencies]
wasm-bindgen-test = "0.3.56"

[package.metadata.cargo-machete]
ignored = ["wasm-bindgen-test"] # used in doc-test
