[package]
name = "wasm-actions-futures"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[features]

[dependencies]
js-sys = { version = "0.3.83" }
wasm-actions-node-sys = { path = "../wasm-actions-node-sys", features = ["microtasks"]}
wasm-bindgen = "0.2.105"

[dev-dependencies]
wasm-bindgen-test = "0.3.55"
