[package]
name = "wasm-actions"
version = "0.6.1"
edition = "2021"

[lib]
crate-type = ["rlib"]

[features]
default = ["derive"]
testing = ["wasm-actions-prelude/testing"]
derive = ["wasm-actions-prelude/derive", "wasm-actions-derive", "wasm-bindgen-futures"]

[dependencies]
wasm-actions-core = { path = "../wasm-actions-core" }
wasm-actions-derive = { path = "../wasm-actions-derive", optional = true }
wasm-actions-log = { path = "../wasm-actions-log" }
wasm-actions-macro = { path = "../wasm-actions-macro" }
wasm-actions-prelude = { path = "../wasm-actions-prelude" }
wasm-bindgen-futures = { version = "0.4.56", optional = true }
async-once-cell = "0.5.4"
log = "0.4.28"

[dev-dependencies]
trybuild = "1.0.114"
wasm-bindgen-test = "0.3.56"
