[package]
name = "wasm-actions-log"
version = "0.6.2"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
log = { version = "0.4.29" }
wasm-actions-core = { path = "../wasm-actions-core" }

[dev-dependencies]
wasm-bindgen-test = "0.3.56"

[features]
default = ["log/kv", "log/std"]
