[package]
name = "wasm-actions-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
js-sys = { version = "0.3" }
wasm-bindgen-futures = "0.4.55"

[dev-dependencies]
wasm-bindgen-test = "0.3.50"
