[package]
name = "wasm-actions-core"
version = "0.6.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[features]
default = []
crypto = [
    "web-sys/Crypto"
]

[dependencies]
wasm-bindgen = "0.2.106"
js-sys = { version = "0.3.83" }
wasm-bindgen-futures = "0.4.56"
web-sys = { version = "0.3.83", default-features = false, optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.56"
