[package]
name = "wasm-actions-core"
version = "0.7.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[features]
default = []
crypto = [
    "web-sys/Crypto"
]

[dependencies]
wasm-bindgen = "0.2.106"
js-sys = { version = "0.3.83" }
web-sys = { version = "0.3.83", default-features = false, optional = true }
wasm-actions-node-sys = { path = "../wasm-actions-node-sys", features = ["fs"]}
wasm-actions-futures = { path = "../wasm-actions-futures" }
tokio = { version = "1.48.0", default-features = false, features = ["io-util"]}

[dev-dependencies]
wasm-bindgen-test = "0.3.56"
