name: test / prelude

on:
  pull_request:
    paths:
      - .github/workflows/shared--wasm-pack-test.yaml
      - .github/workflows/test--prelude.yaml
      - Cargo.lock
      - Cargo.toml
      - rust-toolchain.toml
      - crates/wasm-actions-core/**
      - crates/wasm-actions-log/**
      - crates/wasm-actions-macro/**
      - crates/wasm-actions-prelude/**
    
jobs:
  run:
    uses: ./.github/workflows/shared--wasm-pack-test.yaml
    with:
      path: crates/wasm-actions-prelude
