name: test / main

on:
  pull_request:
    paths:
      - .github/workflows/shared--wasm-pack-test.yaml
      - .github/workflows/test--main.yaml
      - Cargo.lock
      - Cargo.toml
      - rust-toolchain.toml
      - crates/wasm-actions/**
      - crates/wasm-actions-*/**

jobs:
  run:
    uses: ./.github/workflows/shared--wasm-pack-test.yaml
    with:
      path: crates/wasm-actions

