name: test / macro

on:
  pull_request:
    paths:
      - .github/workflows/shared--cargo-test.yaml
      - .github/workflows/test--macro.yaml
      - Cargo.lock
      - Cargo.toml
      - rust-toolchain.toml
      - crates/wasm-actions-macro/**
    
jobs:
  run:
    uses: ./.github/workflows/shared--cargo-test.yaml
    with:
      package-name: wasm-actions-macro
