name: test / build

on:
  pull_request:
    paths:
      - .github/workflows/shared--wasm-pack-test.yaml
      - .github/workflows/test--build.yaml
      - Cargo.lock
      - Cargo.toml
      - rust-toolchain.toml
      - crates/wasm-actions-build/**
      - crates/wasm-actions-parse/**
    
jobs:
  run:
    uses: ./.github/workflows/shared--wasm-pack-test.yaml
    with:
      path: crates/wasm-actions-build
