name: test / derive

on:
  pull_request:
    paths:
      - .github/workflows/shared--wasm-pack-test.yaml
      - .github/workflows/test--derive.yaml
      - Cargo.lock
      - Cargo.toml
      - rust-toolchain.toml
      - crates/core/**
      - crates/derive/**
      - crates/macro/**
      - crates/prelude/**
    
jobs:
  run:
    uses: ./.github/workflows/shared--wasm-pack-test.yaml
    with:
      path: crates/derive
